import { formatLedgerDateTime } from '@/utils/formatDate';

export type CommodityPriceRow = {
  id?: number;
  symbol: string;
  quote: string;
  price: number;
  fetchedAt: Date;
  fetchedDate: string;
};

export const BANNER_MARKER = 'AUTO-GENERATED by ledger-cli-ui';

const BANNER = [
  `; ${BANNER_MARKER} price fetcher.`,
  '; Do not edit by hand — this file is overwritten on every refresh.',
  '; Manual price overrides belong in your main journal.',
].join('\n');

// Ledger reads a bare commodity symbol as a run of characters that excludes
// whitespace, digits, and the punctuation it reserves for amount syntax. A name
// outside that set (e.g. `Real Estate`, `1INCH`, `د.إ`) is only legal
// double-quoted. Fetched/manual tickers (`$`, `BTC`, `USD`) contain none of
// these and stay bare, but a canonical substitution can pull in a `commodity`
// target that does — `parseAliasMap` unquotes those targets, so re-quote here.
const RESERVED_COMMODITY_CHARS = /[\s\d.,;:?!+\-*/^&|=<>[\]{}()@"]/;

const renderCommodity = (symbol: string): string =>
  RESERVED_COMMODITY_CHARS.test(symbol) ? `"${symbol}"` : symbol;

export const renderPriceDb = (rows: CommodityPriceRow[]): string => {
  const generatedAt = `; Last regenerated: ${new Date().toISOString()}`;
  const lines = rows.map(
    (r) =>
      `P ${formatLedgerDateTime(r.fetchedAt)} ${renderCommodity(r.symbol)} ${r.price} ${renderCommodity(r.quote)}`
  );
  return [BANNER, generatedAt, '', ...lines, ''].join('\n');
};

export const hasGeneratedBanner = (text: string): boolean =>
  text.includes(BANNER_MARKER);

/**
 * Header for the relocated-definitions file we create. Carries {@link
 * BANNER_MARKER} so {@link hasGeneratedBanner} recognizes a definitions file we
 * generated (and can distinguish it from a hand-authored `definitions.ledger`).
 * Unlike the price DB, this file is safe for the user to edit — the fetcher
 * never rewrites it.
 */
export const DEFINITIONS_BANNER = [
  `; ${BANNER_MARKER} — relocated commodity/account declarations.`,
  '; Safe to edit; the price fetcher never rewrites this file.',
].join('\n');
