import { formatLedgerDateTime } from '@/utils/formatDate';

export type CommodityPriceRow = {
  id?: number;
  symbol: string;
  quote: string;
  price: number;
  fetchedAt: Date;
  fetchedDate: string;
};

export const BANNER_MARKER = 'AUTO-GENERATED by ledger-cli-ui';

const BANNER = [
  `; ${BANNER_MARKER} price fetcher.`,
  '; Do not edit by hand — this file is overwritten on every refresh.',
  '; Manual price overrides belong in your main journal.',
].join('\n');

export const renderPriceDb = (rows: CommodityPriceRow[]): string => {
  const generatedAt = `; Last regenerated: ${new Date().toISOString()}`;
  const lines = rows.map(
    (r) =>
      `P ${formatLedgerDateTime(r.fetchedAt)} ${r.symbol} ${r.price} ${r.quote}`
  );
  return [BANNER, generatedAt, '', ...lines, ''].join('\n');
};

export const hasGeneratedBanner = (text: string): boolean =>
  text.includes(BANNER_MARKER);
