import { promises as fs } from 'fs';
import path from 'path';
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { ManualPriceRepository } from './manualRepository';
import { CommodityMappingRepository } from './mappingRepository';
import {
  CommodityPriceRepository,
  PriceFetchRunRepository,
} from './repository';
import { PriceService } from './service';
import { getJournalDir } from '@/lib/journal/layout';
import { JournalRepository } from '@/lib/journal/repository';
import { UserSettingRepository } from '@/lib/settings/repository';
import { pull, push, resetObjectStore } from '@/lib/storage';
import {
  setupTestDb,
  teardownTestDb,
  type TestDbContext,
} from '@/lib/test-utils/db';

const BACKUP_DEFINITIONS = [
  'commodity KIRT',
  '\talias Kirt',
  '\tnomarket',
  'P 2024/06/30 12:00:00 DAI 61.83 Kirt',
  'account Expenses:Coffee',
  '',
].join('\n');

const GENERATED_PRICE_DB = [
  '; AUTO-GENERATED by ledger-cli-ui price fetcher.',
  'P 2026/07/06 22:59:09 DAI 0.999678 USD',
  '',
].join('\n');

/** Seed a user whose definitions were dropped into `price-db_old.ledger`. */
const seedDroppedDefinitions = async (ctx: TestDbContext, id: string) => {
  await ctx.insertUser(id, id, `${id}@example.com`);
  await new UserSettingRepository(ctx.db).upsertBaseCurrency(id, 'USD');
  await new JournalRepository(ctx.db).setMainFile(id, 'ledger.ledger');
  const dir = getJournalDir(id);
  await fs.mkdir(dir, { recursive: true });
  await fs.writeFile(
    path.join(dir, 'ledger.ledger'),
    'include ./2025.ledger\n',
    'utf-8'
  );
  await fs.writeFile(
    path.join(dir, '2025.ledger'),
    '2025/01/01 x\n  Assets:Cash  1 KIRT\n  Income\n',
    'utf-8'
  );
  await fs.writeFile(
    path.join(dir, 'price-db_old.ledger'),
    BACKUP_DEFINITIONS,
    'utf-8'
  );
  await fs.writeFile(
    path.join(dir, 'price-db.ledger'),
    GENERATED_PRICE_DB,
    'utf-8'
  );
};

describe('PriceService.relocateLegacyDefinitions', () => {
  let ctx: TestDbContext;
  let service: PriceService;

  beforeEach(async () => {
    resetObjectStore();
    ctx = await setupTestDb('prices-defs-');
    service = new PriceService({
      db: ctx.db,
      commodityRepo: new CommodityPriceRepository(ctx.db),
      runRepo: new PriceFetchRunRepository(ctx.db),
      journalRepo: new JournalRepository(ctx.db),
      manualRepo: new ManualPriceRepository(ctx.db),
      mappingRepo: new CommodityMappingRepository(ctx.db),
    });
  });

  afterEach(async () => {
    await teardownTestDb(ctx);
    resetObjectStore();
  });

  it('relocates dropped definitions into an included file and pushes', async () => {
    await seedDroppedDefinitions(ctx, 'bob');
    await push('bob'); // seed canonical so the relocation's pull is non-destructive

    expect(await service.relocateLegacyDefinitions('bob')).toBe('relocated');

    const dir = getJournalDir('bob');
    const defs = await fs.readFile(
      path.join(dir, 'definitions.ledger'),
      'utf-8'
    );
    expect(defs).toContain('commodity KIRT');
    expect(defs).toContain('alias Kirt');
    expect(defs).toContain('account Expenses:Coffee');
    expect(defs).not.toMatch(/^P /m); // prices don't belong in the definitions file

    const main = await fs.readFile(path.join(dir, 'ledger.ledger'), 'utf-8');
    expect(main.split('\n')[0]).toBe('include ./definitions.ledger');

    // Superseded legacy files are gone; the generated file took over.
    await expect(
      fs.access(path.join(dir, 'price-db.ledger'))
    ).rejects.toThrow();
    await expect(
      fs.access(path.join(dir, 'price-db_old.ledger'))
    ).rejects.toThrow();
    await fs.access(path.join(dir, 'generated-prices.ledger'));

    // The relocation persisted to canonical: wipe local, re-pull, confirm.
    await fs.rm(dir, { recursive: true, force: true });
    await pull('bob');
    const pulled = await fs.readFile(
      path.join(dir, 'definitions.ledger'),
      'utf-8'
    );
    expect(pulled).toContain('alias Kirt');
  });

  it('is idempotent — a second call is a no-op', async () => {
    await seedDroppedDefinitions(ctx, 'bob');
    await push('bob');
    expect(await service.relocateLegacyDefinitions('bob')).toBe('relocated');
    expect(await service.relocateLegacyDefinitions('bob')).toBe('skipped');
  });

  it('skips a user with no dropped definitions', async () => {
    await ctx.insertUser('carol', 'carol', 'carol@example.com');
    await new UserSettingRepository(ctx.db).upsertBaseCurrency('carol', 'USD');
    await new JournalRepository(ctx.db).setMainFile('carol', 'ledger.ledger');
    const dir = getJournalDir('carol');
    await fs.mkdir(dir, { recursive: true });
    await fs.writeFile(
      path.join(dir, 'ledger.ledger'),
      '2025/01/01 x\n  Assets:Cash  1 USD\n  Income\n',
      'utf-8'
    );
    await fs.writeFile(
      path.join(dir, 'generated-prices.ledger'),
      GENERATED_PRICE_DB,
      'utf-8'
    );
    await push('carol');

    expect(await service.relocateLegacyDefinitions('carol')).toBe('skipped');
    await expect(
      fs.access(path.join(dir, 'definitions.ledger'))
    ).rejects.toThrow();
  });
});
